name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CHeck out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build Docker Image
      run: docker build -t piseth168/cicdhtmlimage .

    - name: Publish Image to Docker Hub
      run: docker push piseth168/cicdhtmlimage:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull piseth168/cicdhtmlimage:lates

      - name: Delete Old Container
        run: docker rm -f htmlContainer

      - name: Run Docker Container
        run: docker run -d -p 5000:80 --name htmlContainer piseth168/cicdhtmlimage
